# Generated by Django 5.0 on 2023-12-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_applications_age_applications_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interset', models.CharField(default='', max_length=20)),
                ('description', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='applications',
            name='interests',
        ),
        migrations.AddField(
            model_name='applications',
            name='interests',
            field=models.ManyToManyField(to='home.interests'),
        ),
    ]
