# Generated by Django 5.0 on 2023-12-25 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_interests_remove_applications_interests_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField(auto_now_add=True)),
                ('female_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='female_match', to='home.applications')),
                ('male_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='male_match', to='home.applications')),
            ],
        ),
    ]
