# Generated by Django 5.0 on 2023-12-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='age_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='interest_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='total_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
