# Generated by Django 5.0 on 2023-12-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_match_age_score_match_interest_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
