# Generated by Django 5.0 on 2023-12-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_match_match_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='campus',
            field=models.CharField(blank=True, choices=[('maincampus', 'maincampus'), ('soe', 'soe')], max_length=15),
        ),
        migrations.AddField(
            model_name='applications',
            name='match_with_same_campus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applications',
            name='match_with_same_year',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applications',
            name='year',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
    ]
